prod-area up : fix

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -43,7 +43,7 @@ jobs:
           docker build -t "$IMAGE_NAME" .
           docker push "$IMAGE_NAME"
           echo "${IMAGE_NAME}" > image_to_deploy.txt
-          
+
       - name: Upload image tag artifact
         uses: actions/upload-artifact@v4
         with:
@@ -59,10 +59,15 @@ jobs:
         uses: actions/download-artifact@v4
         with:
           name: image-tag
+          path: .
 
       - name: Read image name to env
         run: |
           IMAGE=$(cat image_to_deploy.txt)
+          if [ -z "$IMAGE" ]; then
+            echo "❌ ERROR: IMAGE_TO_DEPLOY is empty!"
+            exit 1
+          fi
           echo "IMAGE_TO_DEPLOY=$IMAGE" >> $GITHUB_ENV
 
       - name: Deploy to EC2
